### ISSUE TITLE
Avoid potential dependency conflicts between ahmia-index and urllib3

### ISSUE THREAD

**Issue by NeolithEra** [ahmia/ahmia-index#10]
Hi, as shown in the following full dependency graph of  **_ahmia-index_**, ahmia-index requires _**urllib3**_ (the latest version)， while the installed version of **_requests_**(2.22.0) requires _**urllib3>=1.21.1,<1.26**_.

According to Pip's “first found wins” installation strategy, _**urllib3 1.25.3**_ is the actually installed version.  

Although the first found package version _**urllib3 1.25.3**_ just satisfies the later dependency constraint (_**urllib3>=1.21.1, <1.26**_), it will lead to a build failure once developers release a newer version of urllib3.

### Dependency tree--------
```
ahmia-index(version range:)
| +-beautifulsoup4(version range:==4.6.0)
| +-certifi(version range:==2017.4.17)
| +-chardet(version range:==3.0.4)
| +-idna(version range:==2.5)
| +-python-decouple(version range:==3.1)
| +-requests(version range:>=2.20.0)
| | +-chardet(version range:>=3.0.2,<3.1.0)
| | +-idna(version range:>=2.5,<2.9)
| | +-urllib3(version range:>=1.21.1,<1.26)
| | +-certifi(version range:>=2017.4.17)
| +-urllib3(version range:>=1.24.2)
```

Thanks for your attention.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Solution
1.	Fix your direct dependencies to be **_urllib3>=1.21.1,<1.26_** and **_requests==2.22.0_**, to remove this conflict. 
        I have checked this revision will not affect your downstream projects now.

2.	Remove your direct dependency urllib3, and use the urllib3 transitively introduced by urllib3.

@juhanurmi    Please let me know your choice, I will pull a request to fix this problem.
Build a good dependency ecosystem for python projects is our common goal ^_^.

**Comment by juhanurmi** [comment]
Thanks @NeolithEra for you comments!

We could fix this issue with the solution 1.

Thanks,
Juha
