### ISSUE TITLE
mappings_tor.json

### ISSUE THREAD

**Issue by mynksh** [ahmia/ahmia-index#11]
unable to map this with current version of Elasticsearch (7.7)

**Comment by mynksh** [comment]
Change '**doc**' in "mapping_tor.json" to '**_doc**' & add "**?include_type_name=true**" in request URL

**Comment by samip5** [comment]
Just note that `?include_type_name=true` is deprecated.

`Warning: 299 Elasticsearch-7.17.9-ef48222227ee6b9e70e502f0f0daa52435ee634d "[types removal] Using include_type_name in create index requests is deprecated. The parameter will be removed in the next major version."`
